---
# Default values for analytical-platform-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/ministryofjustice/analytical-platform-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "ui"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}

tolerations: []

affinity: {}

app:
  environment:
    - name: DJANGO_SETTINGS_MODULE
      value: ap.settings
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: ui-rds
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ui-rds
          key: password
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: ui-rds
          key: address
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: ui-rds
          key: port
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: ui-app-secrets
          key: secret-key
    - name: SENTRY_DSN
      valueFrom:
        secretKeyRef:
          name: ui-sentry-dsn
          key: dsn
  port: 8000

reverseProxy:
  image:
    repository: "docker.io/nginxinc/nginx-unprivileged"
    tag: "1.27.0-alpine3.19"
  port: 8080
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 101
