---
services:
  postgres:
    image: docker.io/library/postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: ap
      POSTGRES_PASSWORD: ap
      POSTGRES_DB: ap
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ap"]
      interval: 5s
      timeout: 5s
      retries: 5
