---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/gitleaks/gitleaks
    rev: 39fdb480a06768cc41a84ef86959c07ff33091c4  # frozen: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 455f64b32459518aa82ec33b63f799ed048d65a9  # frozen: v0.12.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

exclude: .devcontainer/devcontainer-lock.json
