---
extends: default

rules:
  comments: disable
  line-length:
    level: warning
    allow-non-breakable-inline-mappings: true
  truthy: disable

ignore:
  - '**/chart/templates/*.yaml'
  - '**/chart/templates/tests/*.yaml'
