[project]
name = "analytical-platform-ui"
version = "0.2.0"
description = "Analytical Platform UI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authlib==1.6.5",
    "boto3==1.40.67",
    "django==5.2.8",
    "django-extensions==4.1",
    "django-structlog==10.0.0",
    "gunicorn==23.0.0",
    "psycopg[binary]==3.2.12",
    "pyjwt==2.10.1",
    "python-dotenv==1.2.1",
    "requests==2.32.5",
    "sentry-sdk==2.43.0",
    "uvicorn[standard]==0.38.0",
]


[dependency-groups]
dev = [
    "django-debug-toolbar==6.1.0",
    "ipython>=9.7.0",
    "model-bakery==1.20.5",
    "moto[all]==5.1.16",
    "pre-commit==4.3.0",
    "pytest==8.4.2",
    "pytest-django==4.11.1",
    "pytest-dotenv==0.5.2",
    "ruff==0.14.5",
]


[tool.ruff]
line-length = 100


[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.pytest.ini_options]
addopts = "-v --tb=auto --ds=ap.settings.test"
testpaths = ["tests"]
