---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "analytical-platform-ui.fullname" . }}-nginx-config
  labels:
    {{- include "analytical-platform-ui.labels" . | nindent 4 }}
data:
  default.conf:
    upstream ui {
        server localhost:{{ .Values.app.port }};
    }

    server {
        listen {{ .Values.reverseProxy.port }};

        location /nginx-health {
            access_log off;
            return 200 "healthy\n";
        }

        location /static/ {
            root /usr/share/nginx/html;
        }

        location / {
            try_files $uri @ui;
        }

        location @ui {
            proxy_pass http://ui;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }
