# Generated by Django 5.1 on 2024-09-03 16:06

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "entity",
                    models.CharField(
                        choices=[("database", "Database"), ("table", "Table")], max_length=255
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Text displayed to users when selecting access levels",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ("name", "entity"),
                "unique_together": {("name", "entity")},
            },
        ),
        migrations.CreateModel(
            name="DatabaseAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grantable_permissions",
                    models.ManyToManyField(
                        limit_choices_to={"entity": "database"},
                        related_name="grantable_database_access_set",
                        to="database_access.permission",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        limit_choices_to={"entity": "database"},
                        related_name="database_access_set",
                        to="database_access.permission",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="TableAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "database_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_access",
                        to="database_access.databaseaccess",
                    ),
                ),
                (
                    "grantable_permissions",
                    models.ManyToManyField(
                        limit_choices_to={"entity": "table"},
                        related_name="grantable_table_access_set",
                        to="database_access.permission",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        limit_choices_to={"entity": "table"},
                        related_name="table_access_set",
                        to="database_access.permission",
                    ),
                ),
            ],
            options={
                "unique_together": {("database_access", "name")},
            },
        ),
    ]
