# Generated by Django 5.1 on 2024-09-03 16:07

from django.db import migrations


def forwards(apps, schema_editor):
    Permission = apps.get_model("database_access", "Permission")
    Permission.objects.bulk_create(
        [
            Permission(name="SELECT", entity="table", display_name="Select"),
            Permission(name="SELECT", entity="database", display_name="Select"),
            Permission(name="DESCRIBE", entity="database", display_name="Select"),
        ]
    )


def backwards(apps, schema_editor):
    Permission = apps.get_model("database_access", "Permission")
    Permission.objects.filter(
        name__in=["SELECT", "DESCRIBE"], entity__in=["table", "database"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("database_access", "0001_initial"),
    ]

    operations = [migrations.RunPython(code=forwards, reverse_code=backwards)]
