# Generated by Django 4.2.15 on 2024-08-22 11:13

from django.db import migrations


def forwards(apps, schema_editor):
    AccessLevel = apps.get_model("database_access", "AccessLevel")
    for access_level in [
        ("DESCRIBE", "database", False),
        ("DESCRIBE", "database", True),
        ("SELECT", "table", True),
        ("SELECT", "table", False),
    ]:
        AccessLevel.objects.get_or_create(
            name=access_level[0],
            entity=access_level[1],
            grantable=access_level[2],
        )


def backwards(apps, schema_editor):
    AccessLevel = apps.get_model("database_access", "AccessLevel")
    AccessLevel.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("database_access", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
