# Generated by Django 5.1 on 2024-09-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_access", "0002_intial_access_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslevel",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Text displayed to users when selecting access levels",
                max_length=255,
            ),
        ),
    ]
