# Generated by Django 5.1 on 2024-09-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_access", "0003_accesslevel_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="databaseaccess",
            name="access_levels",
        ),
        migrations.RemoveField(
            model_name="tableaccess",
            name="access_levels",
        ),
        migrations.AddField(
            model_name="databaseaccess",
            name="grantable_permissions",
            field=models.ManyToManyField(
                limit_choices_to={"entity": "database"},
                related_name="grantable_database_access_set",
                to="database_access.accesslevel",
            ),
        ),
        migrations.AddField(
            model_name="databaseaccess",
            name="permissions",
            field=models.ManyToManyField(
                limit_choices_to={"entity": "database"},
                related_name="database_access_set",
                to="database_access.accesslevel",
            ),
        ),
        migrations.AddField(
            model_name="tableaccess",
            name="grantable_permissions",
            field=models.ManyToManyField(
                limit_choices_to={"entity": "table"},
                related_name="grantable_table_access_set",
                to="database_access.accesslevel",
            ),
        ),
        migrations.AddField(
            model_name="tableaccess",
            name="permissions",
            field=models.ManyToManyField(
                limit_choices_to={"entity": "table"},
                related_name="table_access_set",
                to="database_access.accesslevel",
            ),
        ),
    ]
