# Generated by Django 5.1 on 2024-09-03 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database_access", "0004_remove_databaseaccess_access_levels_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accesslevel",
            unique_together={("name", "entity")},
        ),
        migrations.RemoveField(
            model_name="accesslevel",
            name="grantable",
        ),
    ]
