# Generated by Django 5.1 on 2024-09-03 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database_access", "0005_alter_accesslevel_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AccessLevel",
            new_name="Permission",
        ),
    ]
