# Generated by Django 4.2.7 on 2024-02-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_datasource"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="is_quicksight_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
