# Generated by Django 4.2.11 on 2024-04-10 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("name",)},
        ),
    ]
