# Generated by Django 5.2.5 on 2025-09-03 15:03

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RAMShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(help_text="Resource Share Name", max_length=256)),
                (
                    "arn",
                    models.CharField(help_text="Resource Share ARN", max_length=512, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("ACTIVE", "ACTIVE"),
                            ("FAILED", "FAILED"),
                            ("DELETING", "DELETING"),
                            ("DELETED", "DELETED"),
                        ],
                        help_text="Status of the Resource Share",
                        max_length=64,
                    ),
                ),
                ("account_id", models.CharField(help_text="AWS Account ID", max_length=12)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
