# Generated by Django 5.2.5 on 2025-09-04 15:10

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "arn",
                    models.CharField(help_text="Resource Share ARN", max_length=512, unique=True),
                ),
                ("resource_type", models.CharField(help_text="Resource Type", max_length=128)),
                ("account_id", models.CharField(help_text="AWS Account ID", max_length=12)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
