# Generated by Django 5.1 on 2024-09-20 16:23

from django.db import migrations


def update_usernames(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        email, domain = user.email.split("@")
        domain = domain.lower()
        user.username = f"{email}@{domain}"
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(code=update_usernames, reverse_code=migrations.RunPython.noop),
    ]
