---
name: Build and Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build Image
        id: build_image
        uses: docker/build-push-action@16ebe778df0e7752d2cfcbd924afdbbd89c1a755 # v6.6.1
        with:
          file: container/Dockerfile
          push: false
          load: true
          tags: dashboard

      - name: Run Python Tests
        id: run_python_tests
        run: |
          docker compose --file contrib/docker-compose-test.yml run --rm interfaces
        env:
          NETWORK: default
          IMAGE_TAG: dashboard
