---
name: 🔖 Chart Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  chart-release:
    name: Chart Release
    permissions:
      actions: read
      attestations: write
      contents: write
      id-token: write
      packages: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-chart-release.yml@949059b3345aaf08170204e57a010324f03a985b # v4.5.0
    with:
      chart-name: analytical-platform-ui
