---
name: 🔖 Chart Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  chart-release:
    name: Chart Release
    permissions:
      actions: read
      attestations: write
      contents: write
      id-token: write
      packages: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-chart-release.yml@4ea6d39143a59e9717cf49fba53b733dca1e17b0 # v4.7.1
    with:
      chart-name: analytical-platform-ui
