---
name: 🦝 Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@0c3b5555edfbbb10220ed435359dfd6769ad79ed # v3.2.0
    with:
      # VALIDATE_CHECKOV: false # Disabling while in discovery
      # VALIDATE_KUBERNETES_KUBECONFORM is set to false as it cannot process Helm charts
      super-linter-variables: |
        {
          "VALIDATE_CHECKOV": false,
          "VALIDATE_DOCKERFILE_HADOLINT": false,
          "VALIDATE_HTML": false,
          "VALIDATE_JSCPD": false,
          "VALIDATE_KUBERNETES_KUBECONFORM": false,
          "VALIDATE_PYTHON_BLACK": false,
          "VALIDATE_PYTHON_ISORT": false,
          "VALIDATE_PYTHON_PYINK": false,
          "VALIDATE_PYTHON_PYLINT": false,
          "VALIDATE_PYTHON_MYPY": false,
          "VALIDATE_YAML": false
        }
