---
name: 🦝 Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@68ce2de03822a2ca9c6976e558331cd362271155 # v5.1.0
    with:
      # VALIDATE_CHECKOV: false # Disabling while in discovery
      # VALIDATE_KUBERNETES_KUBECONFORM is set to false as it cannot process Helm charts
      # Various Python linters are disabled as we are using Ruff
      super-linter-variables: |
        {
          "VALIDATE_CHECKOV": false,
          "VALIDATE_DOCKERFILE_HADOLINT": false,
          "VALIDATE_HTML": false,
          "VALIDATE_HTML_PRETTIER": false,
          "VALIDATE_JSCPD": false,
          "VALIDATE_KUBERNETES_KUBEFORM": false,
          "VALIDATE_KUBERNETES_KUBECONFORM": false,
          "VALIDATE_PYTHON_BLACK": false,
          "VALIDATE_PYTHON_ISORT": false,
          "VALIDATE_PYTHON_FLAKE8": false,
          "VALIDATE_PYTHON_PYINK": false,
          "VALIDATE_PYTHON_PYLINT": false,
          "VALIDATE_PYTHON_MYPY": false,
          "VALIDATE_YAML": false
        }
