---
name: 🧪 Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Build Image
        id: build_image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: Dockerfile
          push: false
          load: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          build-args: |
            BUILD_DEV=true

      - name: Run Python Tests
        id: run_python_tests
        run: |
          docker compose --file contrib/docker-compose-test.yml run --rm interfaces
        env:
          NETWORK: default
          CONTAINER_IMAGE_NAME: ghcr.io/${{ github.repository }}
          CONTAINER_IMAGE_TAG: ${{ github.sha }}
